// src/components/PrivacyPolicy.js

import React from 'react';
import "../assets/styles/PrivacyPolicy.css";

const PrivacyPolicy = () => {
  return (
    <div className="privacy-policy-container">
      <h1>Privacy Policy</h1>
      <p>Effective date: July 30, 2024</p>
      
      <p>Skill4ge ("us", "we", or "our") operates the https://www.skill4ge.com/ website and the Skill4ge App mobile application (the "Service").</p>
      <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
      <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms of Service.</p>
      
      <h2>Definitions</h2>
      <ul>
        <li><strong>Service:</strong> Service means the https://www.skill4ge.com/ website, any website managed or hosted by Skill4ge, and the Skill4ge App mobile application operated by Skill4ge.</li>
        <li><strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
        <li><strong>Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Cookies:</strong> Cookies are small pieces of data stored on your device (computer or mobile device).</li>
        <li><strong>Data Controller:</strong> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information is processed.</li>
        <li><strong>Data Processors (or Service Providers):</strong> Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
        <li><strong>Data Subject (or User):</strong> Data Subject is any living individual who is using our Service and is the subject of Personal Data.</li>
      </ul>

      <h2>Information Collection and Use</h2>
      <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Cookies and Usage Data</li>
      </ul>
      <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt-out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>
      
      <h4>Usage Data</h4>
      <p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (“Usage Data”).</p>
      <p>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

      <h4>Location Data</h4>
      <p>We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customise our Service. You can enable or disable location services when you use our Service at any time, through your device settings.</p>

      <h4>Tracking & Cookies Data</h4>
      <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
      <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyse our Service.</p>

      <h2>Use of Data</h2>
      <p>Skill4ge uses the collected data for various purposes:</p>
      <ul>
        <li>To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To provide customer support</li>
        <li>To gather analysis or valuable information so that we can improve our Service</li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent and address technical issues</li>
        <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
        <li>To personalise your experience (your information helps us to better respond to your individual needs)</li>
        <li>For research into learning and/or teaching and/or online engagement</li>
      </ul>

      <h2>Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h2>
      <p>If you are from the European Economic Area (EEA), Skill4ge's legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
      
      <h2>Transfer of Data</h2>
      <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
      
      <h2>Disclosure of Data</h2>
      <p>Skill4ge may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul>
        <li>To comply with a legal obligation</li>
        <li>To protect and defend the rights or property of Skill4ge</li>
        <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>To protect the personal safety of users of the Service or the public</li>
        <li>To protect against legal liability</li>
      </ul>

      <h2>Security of Data</h2>
      <p>We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.</p>
      
      <h2>“Do Not Track” Signals</h2>
      <p>We do not support Do Not Track (“DNT”). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>

      <h2>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
      <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Skill4ge aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
      
      <h2>Service Providers</h2>
      <p>We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), to provide the Service on our behalf, to perform Service-related services or to assist us in analysing how our Service is used.</p>
      
      <h2>Links to Other Sites</h2>
      <p>Our Service may contain links to other sites that are not operated by us. We strongly advise you to review the Privacy Policy of every site you visit.</p>
      
      <h2>Children’s Privacy</h2>
      <p>We do not knowingly collect personally identifiable information from anyone under the age of 18 through the Marketplace. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
      
      <h2>Changes to This Privacy Policy</h2>
      <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
      
      <h2>Contact</h2>
      <p>If you have any questions about this Privacy Policy, please contact us:</p>
      <p>Email: contact@skill4ge.com</p>
    </div>
  );
};

export default PrivacyPolicy;
